### PR TITLE
Fix Windows compatibility

### LINKED ISSUE #64: Fix tests on Windows
https://travis-ci.org/sindresorhus/cpy/jobs/544113989

### PR DESCRIPTION
**Pull request by brandon93s**
Resolves #64

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -175,19 +179,14 @@ test('rename filenames using a function', async t => {
...
-	const error = await t.throwsAsync(cpy('license', t.context.EPERM), /EPERM/);
-	t.notRegex(error.message, /glob/);
-});
-
 test('cp-file errors are CpyErrors', async t => {
-	const error = await t.throwsAsync(cpy('license', t.context.EPERM), /EPERM/);
-	t.true(error instanceof CpyError);
+	const cpy = cpyMockedError('cp-file');
+	await t.throwsAsync(cpy('license', t.context.dir), {message: /cp-file/, instanceOf: CpyError});
 });
```
Comment (brandon93s) [inline test.js:186]: These tests are checking for proper handling of exceptions thrown by dependencies.  Previously, the test were implemented with the contrived scenario of a no-access directory which would force these modules to fail: `fs.mkdirSync(t.context.EPERM, 0);` on *nix systems.  This has been replaced with mocking of the dependencies to fail immediately.  With this, the additional `cp-file + glob` test also becomes redundant. 

While a similarly contrived example could have been created for Windows ( e.g. writing to a known folder ) successful test execution would have been dependent on the environment the test was run in ( e.g. elevated shell ).

File: index.js [hunk 2]
```diff
@@ -52,7 +51,9 @@ const preprocessDestinationPath = (source, destination, options) => {
 	}
 
 	if (options.parents) {
-		return path.join(destination, dirname, basename);
+		const dirname = path.dirname(source);
+		const parsedDirectory = path.parse(dirname);
+		return path.join(destination, dirname.replace(parsedDirectory.root, path.sep), basename);
```
Comment (brandon93s) [inline index.js:56]: `destination` and `dirname` can both be absolute paths.  When this occurs you end up with the following:

```sh
# MacOS & Linux
/tmp/example + /tmp/example/cwd => /tmp/example/tmp/example/cwd

# Windows
C:\\tmp\\example + C:\\tmp\\example\\cwd => C:\\tmp\\example\\C:\\tmp\\example\\cwd
```

The resulting Windows path is invalid.  This strips the root ( `C:\\` ) from the directory path before joining by replacing it with the path seperator.  This will be a NOOP on non-Windows.

Comment (sindresorhus) [reply index.js:56]: Good catch. Would you be able to add a test for that?

Comment (brandon93s) [reply index.js:56]: This is covered by the 'path structure' test which was failing prior to this fix.

**Comment by sindresorhus** [comment]
Thanks for fixing this :)
